#数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gymmanager?characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

# tomcat 参数
server:
  port: 8080
  tomcat:
    max-http-form-post-size: 5MB

#日志
logging:
  level:
    root: info
    com.scut.indoorLocation.dao: trace

